version: '3.2'
services:
  web:
    image: "mohamnag/nginx-file-browser"
    network_mode: bridge
    ports:
      - ${WEB_PORT}:80
    volumes:
      - type: bind
        source: ${MUSIC_PATH}
        target: /opt/www/files/
    restart: always
  playlist:
    image: "dreamworkerln/m3u8gen-playlist"
    network_mode: bridge
    environment:
      m3u8gen.init.host: ${HOST_NAME}
      m3u8gen.init.port: ${WEB_PORT}
    ports:
      - ${PLAYLIST_PORT}:80    
    volumes:
      - type: bind
        source: ${MUSIC_PATH}
        target: /music/
    restart: always